djangoProject1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from market.views import get_products

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('market/', include('market.urls', namespace='market')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/urls.py
from django.urls import path

from market.views import get_products, get_product, index

app_name = 'market'

urlpatterns = [
    path('products/', get_products, name='get_products'),
    path('products/<int:product_id>/', get_product, name='get_product'),
    path('items/', index, name='index'),
]

market/models.py
from django.db import models


# Create your models here.


class Author(models.Model):
    name = models.CharField(max_length=255, verbose_name="Author Name")

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='Category Name')

    def __str__(self):
        return self.name


class Books(models.Model):
    category = models.ManyToManyField(Category, verbose_name="Categories")
    author = models.ForeignKey(Author, verbose_name="Author Name", on_delete=models.CASCADE,
                               null=True, blank=True)

    name = models.CharField(max_length=255, verbose_name="Book Name")
    page_count = models.IntegerField(verbose_name="Number of Pages")
    price = models.DecimalField(max_digits=5, decimal_places=2, verbose_name="Price")
    image = models.ImageField(upload_to='Books/', null=True, blank=True, verbose_name="Book Image")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Book'
        verbose_name_plural = 'Books'
        ordering = ['id', 'name', 'price', 'page_count', 'author']
        indexes = [
            models.Index(fields=['id'], name='id'),
            models.Index(fields=['name'], name='name'),
            models.Index(fields=['price'], name='price'),
            models.Index(fields=['page_count'], name='page_count'),
            models.Index(fields=['author'], name='author')
        ]
        constraints = [
            models.UniqueConstraint(fields=['id', 'name', 'author'], name='unique_book')
        ]

market/views.py
from django.core.paginator import Paginator, Page
from django.forms import model_to_dict
from django.http import JsonResponse, HttpResponse, Http404
from django.shortcuts import render, get_object_or_404

from market import models
from market.models import Books


def get_products(request):
    products = Books.objects.all()
    return JsonResponse(list(products.values()), safe=False)


def get_product(request, product_id):
    # product = Books.objects.filter(id=product_id).first()
    product = get_object_or_404(Books, id=product_id)
    return render(request, 'products/detail.html', {'product': product})


def index(request):
    queryset = Books.objects.all()
    paginator = Paginator(queryset, 3)
    page_number = int(request.GET.get('page', 1))
    page: Page = paginator.get_page(page_number)
    return render(request, 'index.html', {'page': page})

market/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book Pages</title>
</head>
<body>
    <h1>Here Should be list of Books:</h1>
    <div>{{ request.GET.name }}</div>

    <div>
        <ul>
            {% for product in page.object_list %}
                <li><a href="{% url 'market:get_product' product.id %}">{{ product.name }}"</a></li>
            {% endfor %}
        </ul>
        {% if page.has_next %}
            <div>
                <a href="{% url 'market:index' %}?page={{ page.next_page_number}}">Next Page</a>
            </div>
        {% endif %}

        {% if page.has_previous %}
            <div>
                <a href="{% url 'market:index' %}?page={{ page.previous_page_number}}">Previous Page</a>
            </div>
        {% endif %}
    </div>
</body>
</html>

market/templates/products/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Product - {{ product.name }}</title>
</head>
<body>
    <h1>Book Name: {{ product.name }}</h1>
    <p>Book Page Count: {{ product.page_count }}</p>
    <h3>Book Category's:</h3>
    <p>{{ product.category.all|join:", " }}</p>
    <p>Book Author: {{ product.author }}</p>
    <p>Book Price: {{ product.price }}</p>
    <p>Book Image: <img src="{{ product.image.url }}" alt="{{ product.name }}"></p>

</body>
</html>